account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.registration_view, name="home"),
    # path('admin/', admin.site.urls),
    path('account/', views.account_view, name="account"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('must-authenticate/', views.must_authenticate_view, name="must_authenticate"),
    path('register/', views.registration_view, name="register"),
    path('phone-otp/', views.phone_otp, name="phone_otp"),
    path('forgot-password/', views.forgot_password, name="forgot_password"),
    path('forgot-password-otp/', views.forgot_password_otp, name="forgot_password_otp"),
    path('forgot-password-new-password/', views.forgot_password_new_password, name="forgot_password_new_password"),
    path('reset-password/', views.reset_password, name="reset_password"),
    path('check-username/', views.check_username, name="check_username"),
    path('check-email/', views.check_email, name="check_email"),

    # path('auto_register/', views.auto_registration_view, name="auto_register"),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from dashboard import views

app_name = "dashboard"

urlpatterns = [
    path('', views.index, name="index"),   
    path('calender', views.calender, name="calender"),
    path('create-room', views.create_room, name="create_room"),
    path('offer-room', views.RoomOfferCreateView.as_view(), name="offer_room"),
    path('confirm-booking/', views.confirm_booking,name='confirm_booking'),
    path('invoice/<id>', views.booking_invoice,name='booking_invoice'),


    path('booking-room', views.booking_room, name="booking_room"),
    path('booking-listview', views.BookingListView.as_view(),name='booking_list_view'),
    path('online-booking-listview', views.OnlineBookingListView.as_view(),name='online_booking_list_view'),

    path('update-room/<int:id>', views.update_room,name='update_room'),
    path('delete-room/<int:id>', views.delete_room,name='delete_room'),

    path('list-room', views.room_list_view, name="room_list_view"),
    path('create-customer-ajax', views.create_customer_ajax, name="create_customer_ajax"),
    path('check-room-availabilty', views.check_room_availabilty, name="check_room_availabilty"),
    # path('get-notification',views.get_notification,name='get_notification',),
    path('account-autocomplete',views.account_autocomplete.as_view(),name='account_autocomplete',),

    path('get-extra-bed', views.get_extra_bed, name="get_extra_bed"),
    path('offer-list-view', views.OfferListView.as_view(),name='offer_list_view'),
    path('<int:id>/delete-offer', views.delete_offer,name='delete_offer'),
    path('update-offer/<int:id>', views.update_offer,name='update_offer'),
    path('<int:id>/account', views.account_detail_view,name='account_detail_view'),
    path('get-max-guests', views.get_max_guests, name="get_max_guests"),
    path('notifications-ajax', views.notifications_ajax, name="notifications_ajax"),
    path('mark-as-read-notifi-ajax', views.mark_as_read_notifi_ajax, name="mark_as_read_notifi_ajax"),

]

rbs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('admin/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('', include(('web.urls', 'web'), namespace='web')),
    path('accounts/', include(('account.urls', 'account'), namespace='account')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings
from django.contrib.auth.models import PermissionsMixin

class MyAccountManager(BaseUserManager):
    def create_user(self, username,email, password):
        if not username:
            raise ValueError('Users must have a username')

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=username,
            email=self.normalize_email(email),            
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username,password):
        user = self.create_user(
            username=username,
            email="hashidsharafkoori@gmail.com",
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60,)
    username = models.CharField(max_length=60, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30,)
    last_name = models.CharField(max_length=30,)
    phone = models.CharField(max_length=20,unique=False)
    address = models.CharField(max_length=140,)

    USERNAME_FIELD = 'username'

    # REQUIRED_FIELDS = []

    objects = MyAccountManager()

    def __str__(self):
        return str(self.username)

    def has_perm(self,perm,obj=None):
        return self.is_admin
        
    def has_module_perms(self,app_label):
        return True
        

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from account.models import Account


class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, widget=forms.EmailInput(attrs={'class':'form-control'},))
	password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control pwstrength','data-indicator':'pwindicator'},))
	password2 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control'},))

	class Meta:
		model = Account
		fields = ('email', 'username','address','phone','first_name','last_name')
		widgets= {
			'username' : forms.TextInput(attrs={'class': 'required form-control',}),
			'first_name' : forms.TextInput(attrs={'class': 'required form-control',}),
			'last_name' : forms.TextInput(attrs={'class': 'required form-control',}),
			'address' : forms.Textarea(attrs={'class': 'required form-control',}),
			'phone' : forms.NumberInput(attrs={'class': 'required form-control','type' : 'tel','maxlength' : '10'}),
			
		}
	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'required form-control',}))
	username = forms.CharField(max_length=254, widget=forms.TextInput(attrs={'class':'form-control'},))
	class Meta:
		model = Account
		fields = ('username', 'password')

	def clean(self):
		if self.is_valid():
			username = self.cleaned_data['username']
			password = self.cleaned_data['password']
			if not authenticate(username=username, password=password):
				raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

	class Meta:
		model = Account
		fields = ('email', 'username', )

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from account.forms import RegistrationForm, AccountAuthenticationForm, AccountUpdateForm
# from main.functions import get_pk_id,sendSMS
from .models import *
from random import randint
from django.core import mail
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.http.response import HttpResponse
import json


def registration_view(request):
	context = {}
	user = request.user
	if user.is_authenticated: 
		logout(request)

	if request.POST:
		form = RegistrationForm(request.POST)
		if form.is_valid():
			print("vali ///")
			data = form.save(commit=False)
			otp = str(randint(100000, 999999))
			request.session['first_name'] = data.first_name
			request.session['last_name'] = data.last_name
			request.session['email'] = data.email
			request.session['password1'] = form.cleaned_data.get('password1')
			request.session['password2'] = form.cleaned_data.get('password2')
			request.session['address'] = data.address
			request.session['phone'] = data.phone
			request.session['username'] = data.username
			request.session['otp'] = otp
			email = data.email
			name =  data.first_name + " " + data.last_name
			
			try:
				from_email = "deluxinn.in <ecolumsmarketing@gmail.com>"
				subject = "Your OTP is:" + otp
				text_content = "Yourn OTP is:" + otp
				try:
					msg = EmailMultiAlternatives(subject, text_content, from_email, [email])
					msg.attach_alternative(text_content, "text/html")
					msg.send()
					return redirect('account:phone_otp')
				except:
					pass
			except:
				pass

		else:
			context['registration_form'] = form
	else:
		form = RegistrationForm()
		context['registration_form'] = form
	return render(request, 'dashboard/account/register.html', context)



def phone_otp(request):
	email = str(request.session['email'])
	context = {
		"email" : email
		}
	if request.POST:
		real_otp = str(request.session['otp'])
		otp = request.POST['otp']

		updated_request = request.POST.copy()
		updated_request.update({
			'first_name': request.session['first_name'],
			'last_name': request.session['last_name'],
			'email': request.session['email'],
			'address': request.session['address'],
			'phone': request.session['phone'],
			'password1': request.session['password1'],
			'password2': request.session['password2'],
			'username': request.session['username'],
			})
		form =  RegistrationForm(updated_request)
		if (otp == real_otp) and form.is_valid():
			form.save()
			username = updated_request['username']
			password = updated_request['password1']
			user = authenticate(username=username, password=password)
			login(request, user)

			return redirect("web:index")

	return render(request, "dashboard/account/phone_otp.html",context)

def logout_view(request):
	logout(request)
	return redirect('/')


def login_view(request):
	context = {}
	user = request.user
	if user.is_authenticated: 
		logout(request)
	if request.POST:
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user:
				login(request, user)
				if user.is_admin:
					return redirect("dashboard:index")
				else:
					return redirect("web:index")
	else:
		form = AccountAuthenticationForm()
	context['login_form'] = form
	return render(request, "dashboard/account/login.html", context)


def forgot_password(request):
	context = {}
	user = request.user
	if user.is_authenticated: 
		logout(request)
	if request.POST:
		try:
			request.session['otp_count'] = 5
			email = request.POST['email']
			request.session['email'] = email
			if Account.objects.filter(email=email).exists():
				otp = str(randint(100000, 999999))
				request.session['otp'] = otp
				message = 'your otp is : ' + otp + ','
				try:
					from_email = "deluxinn.in <ecolumsmarketing@gmail.com>"
					subject = "Your OTP is:" + otp
					text_content = "Your OTP is:" + otp

					try:
						msg = EmailMultiAlternatives(subject, text_content, from_email, [email])
						msg.attach_alternative(text_content, "text/html")

						msg.send()
						print("mail sent")
					except:
						pass
				except:
					pass
				
				account = Account.objects.filter(email=email).first()
				request.session.set_expiry(600)
				request.session['account'] = account.pk
				return redirect("account:forgot_password_otp")
			else:
				messages.info(request, 'This email is not registerd')
				return redirect("account:forgot_password")
		except:
			messages.info(request, 'Your Session has time out. please try again')
			return redirect("account:forgot_password")
	return render(request, 'dashboard/account/forgot-password.html', context)


def forgot_password_otp(request):
	email = request.session['email']
	context = {"email":email}
	user = request.user
	if user.is_authenticated: 
		logout(request)
	if request.POST:
		try:
			input_otp = request.POST['otp']
			otp = request.session['otp']
			if input_otp == otp:
				if request.session['otp_count'] < 0:
					del request.session['account']
					del request.session['otp']
					messages.info(request, 'Too many attempts,Please Try again later')
					return redirect("account:forgot_password")
					
				account = request.session['account']	
				user = Account.objects.get(pk=account)			
				login(request, user)
				return redirect("account:forgot_password_new_password")
			else:
				otp_count = request.session['otp_count']
				request.session['otp_count'] = otp_count - 1
				messages.info(request, 'Incorrect OTP')
				if request.session['otp_count'] <= 0:
					del request.session['account']
					del request.session['otp']
					messages.info(request, 'Too many attempts,Please Try again later')
					return redirect("account:forgot_password")
		except:
			messages.info(request, 'Too many attempts,Please Try again later')
			return redirect("account:forgot_password")
	
	return render(request, 'dashboard/account/forgot_password_otp.html', context)

def forgot_password_new_password(request):
	context = {}
	user = request.user
	if request.POST:
		password = request.POST['password']
		try:
			account_pk = request.session["account"]
			account = Account.objects.get(pk = account_pk)
			account.set_password(password)
			account.save()
			login(request, account)
			return redirect("web:index")
		except:
			messages.info(request, 'Your Session has time out. please try again ')
			return redirect("account:forgot_password")
	return render(request, 'dashboard/account/forgot_password_new_password.html', context)



def account_view(request):
	if not request.user.is_authenticated:
			return redirect("login")
	context = {}
	return render(request, "account/account.html", context)

def must_authenticate_view(request):
	return render(request, 'account/must_authenticate.html', {})



def reset_password(request):
	context = {}
	user = request.user
	if user.is_authenticated: 
		if request.POST:
			old_password = request.POST['old_password']
			new_password = request.POST['new_password']
			print(old_password)
			print(new_password)

			if(user.check_password(old_password)):
				print("psswrd checked !!")
				account = Account.objects.get(pk=user.pk)
				print(account)
				account.set_password(new_password)
				account.save()
				logout(request)
				return redirect('/')
			else:
				messages.info(request, 'Incorrect password !')
				return render(request, 'dashboard/account/reset-password.html', context)

		else:	
			return render(request, 'dashboard/account/reset-password.html', context)

	return redirect('/')

def check_username(request):
	user = request.user
	q = request.GET.get('q')
	if(Account.objects.filter(username=q).exists()):
		response_data = {
			"status" : "false",
		}
	else:
		response_data = {
			"status" : "true",
		}
	return HttpResponse(json.dumps(response_data),content_type='application/javascript')



def check_email(request):
	user = request.user
 
	q = request.GET.get('q')
	if(Account.objects.filter(email=q).exists()):
		response_data = {
			"status" : "false",
		}
	else:
		response_data = {
			"status" : "true",
		}
	return HttpResponse(json.dumps(response_data),content_type='application/javascript')

templates/dashboard/account/auth_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<!-- auth-register.html  21 Nov 2019 04:05:01 GMT -->

<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Deluxe - Inn</title>
  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static 'dashboard/css/app.min.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/bundles/jquery-selectric/selectric.css' %}">
  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/css/components.css' %}">
  <!-- Custom style CSS -->
  <link rel="stylesheet" href="{% static 'dashboard/css/custom.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'dashboard/img/icon.png' %}" />
</head>


<body>
  <div class="loader"></div>
  <div id="app">
    <section class="section">
      <div class="container mt-5">
        <div class="row">
          <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
            {% block content %}

            {% endblock %}
          </div>
        </div>
      </div>
    </section>
  </div>
  <!-- General JS Scripts -->
  <script src="{% static 'dashboard/js/app.min.js' %}"></script>
  <!-- JS Libraies -->
  <script src="{% static 'dashboard/bundles/jquery-pwstrength/jquery.pwstrength.min.js' %}"></script>
  <script src="{% static 'dashboard/bundles/jquery-selectric/jquery.selectric.min.js' %}"></script>
  <script src="{% static 'dashboard/js/sweetalert.min.js' %}"></script>

  <!-- Page Specific JS File -->
  <script src="{% static 'dashboard/js/page/auth-register.js' %}"></script>
  <!-- Template JS File -->
  <script src="{% static 'dashboard/js/scripts.js' %}"></script>
  <!-- Custom JS File -->
  <script src="{% static 'dashboard/js/custom.js' %}"></script>
  {% block scripts %} {% endblock %}
</body>

<!-- auth-register.html  21 Nov 2019 04:05:02 GMT -->

</html>

templates/dashboard/account/email_otp.html
<!-- @format -->

{% extends 'dashboard/account/auth_base.html' %} {% block content %}
<div class="card card-primary">
  <div class="card-header">
    <h4>Email verification</h4>
  </div>
  <div class="card-body">
    <form class="" method="POST" action="{% url 'account:email_otp' %}">
      <div class="row">
        <div class="form-group col-12">
          <p>
            Enter the 6-digit verification code from the message sent to
            <b>{{ phone }}</b>
          </p>
          <label for="otp">Enter Your OTP</label>

          <input
            type="text"
            name="otp"
            class="form-control"
            maxlength="254"
            required=""
            id="otp"
          />
          {% csrf_token %}
        </div>
      </div>

      <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg btn-block">
          Verify
        </button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

templates/dashboard/account/login.html
<!-- @format -->

{% extends 'dashboard/account/auth_base.html' %} {% load static %} {% block content %}
      <div class="card card-primary">
        <div class="card-header">
          <h4>Login</h4>
         </div>
         <div class="card-body">
          <form method="POST" action="{% url 'account:login' %}" class="needs-validation" novalidate="">
            <div class="form-group">
              <label for="username">Username</label>
              {{ login_form.username }}
              <div class="invalid-feedback">Please fill in your email</div>
            </div>
            <div class="form-group">
              <div class="d-block">
                <label for="password" class="control-label">Password</label>
                <div class="float-right">
                  <!-- <a href="auth-forgot-password.html" class="text-small">
                    Forgot Password?
                  </a> -->
                </div>
              </div>
              {{ login_form.password }}
              <div class="invalid-feedback">please fill in your password</div>
            </div>
            <div class="form-group">
              <div class="custom-control custom-checkbox">
                <input type="checkbox" name="remember" class="custom-control-input" tabindex="3" id="remember-me" />
                <label class="custom-control-label" for="remember-me">Remember Me</label>
              </div>
            </div>
            <div class="form-group">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                Login
              </button>
            </div>
          </form>
          <!-- <div class="text-center mt-4 mb-3">
            <div class="text-job text-muted">Login With Social</div>
          </div>
          <div class="row sm-gutters">
            <div class="col-6">
              <a class="btn btn-block btn-social btn-facebook">
                <span class="fab fa-facebook"></span> Facebook
              </a>
            </div>
            <div class="col-6">
              <a class="btn btn-block btn-social btn-twitter">
                <span class="fab fa-twitter"></span> Twitter
              </a>
            </div>
          </div> -->
    </div>
  
    </div>

<div class="mt-5 text-muted text-center">
  Don't have an account? <a href="{% url 'account:register' %}">Create One</a><br />
  <a href="{% url 'account:forgot_password' %}">Forgot Password !</a>

</div>

{% endblock %}

templates/dashboard/account/register.html
{% extends 'dashboard/account/auth_base.html' %}
{% load static %}
{% block content %}


<div class="card card-primary">
  <div class="card-header">
    <h4>Register</h4>
  </div>
  <div class="card-body">
    <form class="" method="POST" action="{% url 'account:register' %}">
      <div class="row">
        <div class="form-group col-6">
          <label for="frist_name">First Name</label>
          {{ registration_form.first_name }}
        </div>
        <div class="form-group col-6">
          <label for="last_name">Last Name</label>
          {{ registration_form.last_name }}
        </div>
      </div>
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" id="username" class="form-control check_username" name="username" value=""
          data-url="/account/check-username/" required="required" minlength="6">
        <div class="check_username_msg invalid-feedback" style="display: block;">Not available</div>
        <div class="check_username_msg valid-feedback" style="display: none;">Available</div>

      </div>
      <div class="form-group">
        <label for="address">Address</label>
        {{ registration_form.address }}
        <div class="invalid-feedback">
        </div>
      </div>


      <div class="row">
        <div class="form-group col-6">
          <label for="email">Email</label>
          {{ registration_form.email }}
          <div class="invalid-feedback">
          </div>
        </div>
        <div class="form-group col-6">
          <label for="phone">Phone</label>
          <div class="phone_input">
            {{ registration_form.phone }}
            <span class="code_91">+91</span>
          </div>
          <div class="invalid-feedback">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-6">
          <label for="password" class="d-block">Password</label>
          <!-- <input id="password22" type="password" class="form-control pwstrength" data-indicator="pwindicator"
                        name="password"> -->
          {{ registration_form.password1 }}
          <div id="pwindicator" class="pwindicator">
            <div class="bar"></div>
            <div class="label"></div>
          </div>
        </div>
        <div class="form-group col-6">
          <label for="password2" class="d-block">Password Confirmation</label>
          <!-- <input id="password22" type="password" class="form-control" name="password-confirm"> -->
          {{ registration_form.password2 }}
        </div>
      </div>
      <div class="form-group">
        <!-- <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="agree" class="custom-control-input" id="agree">
                      <label class="custom-control-label" for="agree">I agree with the terms and conditions</label>
                    </div> -->
      </div>
      <div class="form-group">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg btn-block">
          Register
        </button>

      </div>
    </form>
  </div>
  <div class="mb-4 text-muted text-center">
    Already Registered? <a href="{% url 'account:login' %}">Login</a>
  </div>
</div>

{% endblock %}

templates/dashboard/account/reset-password.html
{% extends 'dashboard/account/auth_base.html' %} {% load static %} {% block content %}
<div class="card card-primary">
  <div class="card-header">
    <h4>Reset Password</h4>
  </div>
  <div class="card-body">
    <p class="text-muted">Enter Your New Password</p>
    <p id="messages" style="color: red;">{{message}}</p>
    <form method="POST" action="{% url 'account:reset_password' %}">
      <div class="form-group">
        <label for="old_password">Old Password</label>
        <input id="old_password" type="password" class="form-control pwstrength" data-indicator="pwindicator"
          name="old_password" tabindex="1" required>
        <div id="pwindicator" class="pwindicator">
          <div class="bar"></div>
          <div class="label"></div>
        </div>
      </div>
      <div class="form-group">
        <label for="password">New Password</label>
        <input id="new_password" type="password" class="form-control pwstrength" data-indicator="pwindicator"
          minlength="6" name="new_password" tabindex="2" required>
        <div id="pwindicator" class="pwindicator">
          <div class="bar"></div>
          <div class="label"></div>
        </div>
      </div>
      <div class="form-group">
        <label for="password-confirm">Confirm Password</label>
        <input id="password-confirm" type="password" class="form-control" name="confirm_password" tabindex="3"
          minlength="6" required>
      </div>
      <div class="form-group">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
          Reset Password
        </button>
      </div>
    </form>
    <a class="" href="{% url 'account:forgot_password' %}">forgot password ?</a>
  </div>
</div>
{% endblock %} {% block scripts %}

<script src="{% static 'dashboard/js/jquery.formset.min.js' %}"></script>
<script src="{% static 'dashboard/bundles/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'dashboard/js/page/forms-advanced-forms.js' %}"></script>

<script type="text/javascript">
  $(document).ready(function () {
    $("input[type=text]").focus(function () {
      $(this).select();
    });

    $(".form_set_row").formset({
      prefix: "{{formset.prefix}}",
      formCssClass: "dynamic-formset1",
      addText: "Add",
      addCssClass: "btn btn-primary btn-sm",
      deleteCssClass: "btn btn-danger btn-sm",
      deleteText: "Remove",
      added: function (row) {
        row.find(".form_set_row select").val(null).trigger("change");
        row.find(".select2-selection").click();
      },
    });

    $("form").submit(function (event) {
      event.preventDefault();
      swal({
        title: "Proccessing...!",
        text: "Please wait",
        icon: "info",
        button: false,
      });

      let $this = $(this);
      var url = $this.attr("action");
      var method = $this.attr("method");
      if ($("#password-confirm").val() == $("#new_password").val()) {

        $.ajax({
          type: method,
          url: url,
          dataType: "json",
          contentType: false,
          processData: false,
          data: new FormData(this),

          success: function (data) {
            if (data["status"] == "true") {
              swal({
                title: "Success !",
                text: "Successfully Submited",
                icon: "success",
                button: "ok",
              }).then(function () {
                if (data["redirect_url"]) {
                  location.href = data["redirect_url"];
                }
                if (data["reLoad"]) {
                  location.reload();
                }

                if (data["click_class"]) {
                  $(data["click_class"]).click();
                }
              });
            } else {
              $this.find(".ajax-form-error").text(data["error_message"]);
              swal({
                title: "Try Again !",
                text: data["error_message"],
                icon: "warning",
                button: "OK",
              });
            }
          },
          error: function (data) {
            swal({
              title: "Try Again !",
              text: "something went wrong",
              icon: "warning",
              button: "OK",
            });
          },
        });
      } else {
        swal({
          title: "Try Again !",
          text: "Passwords do not match !",
          icon: "warning",
          button: "OK",
        });
      }
    });
  });

</script>

{% endblock %}