rbs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('admin/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('', include(('web.urls', 'web'), namespace='web')),
    path('accounts/', include(('account.urls', 'account'), namespace='account')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from web import views

app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('order-summary', views.order_summary, name="order_summary"),
    path('paymenthandler/', views.paymenthandler, name='paymenthandler'),
    # path('booking-confirmed/<booking_id>', views.booking_confirmed, name="booking_confirmed"),
    path('get-extra-bed', views.get_extra_bed, name="get_extra_bed"),
    path('check-room-availabilty-web', views.check_room_availabilty_web, name="check_room_availabilty_web"),
    path('create-user-data-ajax', views.create_user_data_ajax, name="create_user_data_ajax"),
    path('terms-and-conditions', views.term_and_conditions, name="term_and_conditions"),
    path('privacy-policy', views.privacy_policy, name="privacy_policy"),
    path('cancellation-policy', views.cancellation_policy, name="cancellation_policy"),



]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings
from django.contrib.auth.models import PermissionsMixin

class MyAccountManager(BaseUserManager):
    def create_user(self, username,email, password):
        if not username:
            raise ValueError('Users must have a username')

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=username,
            email=self.normalize_email(email),            
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username,password):
        user = self.create_user(
            username=username,
            email="hashidsharafkoori@gmail.com",
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60,)
    username = models.CharField(max_length=60, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30,)
    last_name = models.CharField(max_length=30,)
    phone = models.CharField(max_length=20,unique=False)
    address = models.CharField(max_length=140,)

    USERNAME_FIELD = 'username'

    # REQUIRED_FIELDS = []

    objects = MyAccountManager()

    def __str__(self):
        return str(self.username)

    def has_perm(self,perm,obj=None):
        return self.is_admin
        
    def has_module_perms(self,app_label):
        return True
        

templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">

	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<meta name="description" content="">
	<meta name="author" content="">

	<title>DeluxeInn</title>

	<!-- Standard Favicon -->
	<link rel="icon" type="image/x-icon" href="#" />

	<!-- For iPhone 4 Retina display: -->
	<link rel="apple-touch-icon-precomposed" sizes="114x114"
		href="{% static 'web/images//apple-touch-icon-114x114-precomposed.png' %}">

	<!-- For iPad: -->
	<link rel="apple-touch-icon-precomposed" sizes="72x72"
		href="{% static 'web/images//apple-touch-icon-72x72-precomposed.png' %}">

	<!-- For iPhone: -->
	<link rel="apple-touch-icon-precomposed" href="{% static 'web/images//apple-touch-icon-57x57-precomposed.png' %}">

	<!-- Library - Google Font Familys -->

	<!-- Library - Bootstrap v3.3.5 -->
	<link rel="stylesheet" type="text/css" href="{% static 'web/libraries/lib.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'web/libraries/calender/calendar.css' %}">

	<!-- Custom - Common CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/plugins.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/navigation-menu.css' %}">

	<!-- Custom - Theme CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/shortcodes.css' %}" />
    <link rel='shortcut icon' type='image/x-icon' href="{% static 'dashboard/img/icon.png' %}" />

	<!--[if lt IE 9]>
		<script src="{% static 'web/js/html5/respond.min.js"></script>
    <![endif]-->

</head>

<body data-offset="200" data-spy="scroll" data-target=".ow-navigation">
	<!-- Loader -->
	<a id="top"></a>

	<!-- Header Section -->
	<header id="header" class="header-section container-fluid no-padding">
		<!-- Top Header -->
		<div class="top-header container-fluid">
			<!-- Container -->
			<div class="container">
				<div class="row">
					<div class="logo-block col-md-3"><a href="{% url 'web:index' %}" title="DeluxeInn"><img
								src="{% static 'web/images/logo.png' %}" alt="Logo" style="margin-top: -41px;" /></a>
					</div>
					<div class="col-md-9 contact-detail">
						<div class="phone">
							<img src="{% static 'web/images/phone-ic.png' %}" alt="Phone" />
							<h6>contact us</h6>
							<a href="tell:1800234567890" title="7907 555 555">7907 555 555
								|+9144 24327836 <br> 24327837 |
								+91 9962541077 | 9962541190</a>
						</div>
						<div class="address">
							<img src="{% static 'web/images/address-ic.png' %}" alt="Address" />
							<h6>our office</h6>
							<p> 49, Theyagaraya Road,<br>
								Pondy Bazar, Chennai-600017</p>

						</div>
						<div class="menu-search">


						</div>
					</div>
				</div>
			</div><!-- Container /- -->
		</div><!-- Top Header /- -->
		<!-- Menu Block -->
		<div class="menu-block">

			<!-- Container -->
			<div class="container">
				<div class="row">
					<div class="col-md-10 ">
						<nav class="navbar navbar-default ow-navigation ">
							<div class="navbar-header">
								<button aria-controls="navbar" aria-expanded="false" data-target="#navbar"
									data-toggle="collapse" class="navbar-toggle collapsed" type="button">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
								<a href="{% url 'web:index' %}" title="Deluxe Inn" class="navbar-brand"><img
										src="{% static 'web/images/logo.png' %}" alt="Logo"
										style="margin-top: -101px; max-width:50%" /></a>
							</div>
							<div class="navbar-collapse collapse" id="navbar">
								<ul class="nav navbar-nav">
									<li class="dropdown active">
										<a href="{% url 'web:index' %}" title="Home" class="dropdown-toggle" role="button"
											aria-haspopup="true" aria-expanded="false">Home</a>



									</li>
									<li><a href="{% url 'web:index' %}#about" title="About Us">about Us</a></li>
									<li class="dropdown">
										<a href="{% url 'web:index' %}#room" title="Rooms" class="dropdown-toggle" role="button"
											aria-haspopup="true" aria-expanded="false">Rooms</a>


									</li>
									<li><a href="{% url 'web:index' %}#service" title="Services">Services</a></li>
									<li><a href="{% url 'web:index' %}#gallery" title="Gallery">Gallery</a></li>
									<li><a href="{% url 'web:index' %}#contact" title="Contact">Contact</a></li>
									<!-- <li><a href="#booking" title="Book Now">Book now</a></li> -->
								</ul>
							</div>
							
						</nav>
					</div>
					<!-- <div class="col-md-2 book-now">
						<a href="#" title="Book Now">Book Now</a>
					</div> -->
					<!-- <div class="col-md-2 book-now">
						<a href="#" title="Login">Login</a>
					</div> -->
				</div><!-- Row /- -->
				
			</div><!-- Container /- -->
		</div>
	
		
	</header><!-- Header Section /- -->

    {% block content %} 
            
    {% endblock %}

    <div class="footer-section container-fluid no-padding" id="contact">
        <!-- Top Footer -->
		<div class="top-footer container-fluid no-padding">
			<!-- Container -->
			<div class="container">
				<div class="row">
					<aside class="col-md-3 col-sm-12 col-xs-12 ">
						<!-- <h4 class="widget_title">Contact Us</h4> -->
					<div class="footer-navigation">
							
							<p> <a href="#index">Home</a></p>
							<p><a href="#about" title="About Us">About Us</a></p>
							
							<p><a href="#room" title="Rooms" >Rooms</a></p>
							
							<p><a href="#service" title="Services">Services</a></p>
							<p><a href="#contact" title="Contact">Contact</a></p>
							<p><a href="{% url 'web:term_and_conditions' %}" title="Contact">Term and Conditions</a></p>
							<p><a href="{% url 'web:privacy_policy' %}" title="Contact">Privacy Policy</a></p>
							<p><a href="{% url 'web:cancellation_policy' %}" title="Contact">Cancellation Policy</a></p>

					</div>
					</aside>

					<!-- Text Widget -->
					<aside class="col-md-6 col-sm-12 col-xs-12 contact-content">
						<h4 class="widget_title">Contact Us</h4>
					<div class="contact-detail">
						<i class="fa fa-map-marker"></i>
						<h5>Office Address</h5>
						<p>28, Theyagaraya Road,
							Pondy Bazaar,
							T Nagar, Chennai </p>
					</div>
					<div class="contact-detail">
						<i class="fa fa-phone"></i>
						<h5>Phone</h5>
						<p><span>Local: <a href="#">+914424327836</a></span><span>Mobile: <a href="#">9962541190
								</a></span></p>
					</div>
					<div class="contact-detail">
						<i class="fa fa-envelope"></i>
						<h5>Email Address</h5>
						<p><a href="mailto:info@Hotely.com" title="info@Hotely.com">hoteldeluxeinn@yahoo.com</a></p>
					</div>
					<ul>
						<li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>

							<li><a href="#" title="Instagram"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>


						</ul>
					</aside>
					<!-- pages -->


					<!-- Newsletter -->
					<!-- <aside class="col-md-4 col-sm-6 col-xs-6 widget widget_newsletter">

						<form class="contact-form" id="contact_form" action="https://mail-sender.vingb.com/send/c1fcf443-5aa6-4445-b3ca-aa6aa4885d66" method="post">
							<div class="form-group">
								<input type="text" class="form-control" id="input_name" name="enq_name"
									placeholder="Full Name" required="">
							</div>
							<div class="form-group">
								<input type="text" class="form-control" id="input_phone" name="enq_phone"
									placeholder="Phone No" required="">
							</div>
							<div class="form-group">
								<input type="email" class="form-control" id="input_email" name="enq_email"
									placeholder="Email Address" required="">
							</div>
							<div class="form-group">
								<textarea id="textarea_message" class="form-control" rows="5" name="enq_message"
									placeholder="Type here message" required=""></textarea>
							</div>
							<div class="form-group">
								<input id="form_submit" type="submit" value="Send Message">
							</div>
							<div id="alert-msg" class="alert-msg"></div>
						</form>
					</aside>Newsletter /- -->
					<!-- Gallery -->
					<!-- <aside class="col-md-3 col-sm-6 col-xs-6 widget widget_gallery">

						<div class="mapouter">
							<div class="gmap_canvas"><iframe width="400" height="400" id="gmap_canvas"
									src="https://maps.google.com/maps?q=Bank%20Of%20Baroda%2074,%20Sir%20Theagaraya%20Rd,%20Pondy%20Bazaar,%20Parthasarathi%20Puram,%20T.%20Nagar,%20Chennai,%20Tamil%20Nadu%20600017,%20India&t=&z=13&ie=UTF8&iwloc=&output=embed"
									frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a
									href="https://fmovies-online.net"></a><br><a
									href="https://www.embedgooglemap.net"></a>
								<style>
									.gmap_canvas {
										overflow: hidden;
										background: none !important;
									}
								</style>
							</div>
						</div>
					</aside>Gallery /- -->
				</div>
			</div><!-- Container /- -->

		</div><!-- Top Footer -->
        <div class="bottom-footer container-fluid">
            <p>&copy; Copyrights 2021 Deluxe Inn. All Rights Reserved</p>
        </div>
    </div><!-- Footer Section /- -->
	<script src="{% static 'web/js/jquery.min.js' %}"></script>

	<script src="{% static 'web/js/custom.js' %}"></script>
	{% block scripts %}

	{% endblock %}

</body>
</html>

templates/web/booking_confirmed.html
{% extends 'web/base.html' %} 
{% load static %}

{% block content%}
<div class="site-main page-spacing">
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 border-round mt" style="text-align: center;color: #6f6e6e;">
                    <h2 >
                        Your Boooking has been confirmed. <br>
                    </h2>
                    <p>
                        A confirmation Email has been sent to your Email address provided by you.<br>
                    </p> 
                      <p style="font-size: medium;color: #000;">
                        Booking ID: <b>#{{ booking.auto_id }} </b> <br>
                        Order id :<b>#{{ booking.order_id}} </b>
                      </p> 
                    
                </div>
                    
                </div>
            </div>
        </div>

        
        
    </section>
        
</div>
{% endblock %}

templates/web/cancellation_policy.html
{% extends 'web/base.html' %} 
{% load static %}

{% block content%}
<div class="site-main page-spacing">
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <h2>
                            Cancellation Policy
                       </h2>
                       
                        <ol start=1>
                            <p><li>You can cancel your booking by contacting us</li></p>
                            <p><li>5% Charge is applicable on all cancellation.</li>   </p> 
                            <p><li>For Cancellation done prior to 24hr before checkin date,75% is Refundable on regular room.</li>   </p>
                            <p><li>For Cancellation done prior to 24hr before checkin date,50% is Refundable on Discounted room.</li> </p>
                           <p><li>The applicable refund amount will be credited to you within 7-14 working days. </li>   </p> 
                        </ol>
                         </div>
      
  
                
            </div>
        </div>
    </section>
        
</div>
{% endblock %}

templates/web/order_summary.html
{% extends 'web/base.html' %} 
{% load static %}

{% block content%}
<div class="site-main page-spacing">
  <section class="section">
    <div class="container">
      <div class="row mt">
        <div class="col-md-6 ">
          <form action="" method="post">
            {% csrf_token %}
            <div class="form-group col-md-6">
              <label>First name</label>
              {{ custform.first_name }}
            </div>

            <div class="form-group col-md-6">
              <label>Last name</label>
              {{ custform.last_name }}
            </div>

           
            <div class="form-group col-md-6">
              <label>Phone</label>
              {{ custform.phone }}
            </div>

            <div class="form-group col-md-6">
              <label>Email</label>
              {{ custform.email }}
            </div>

            <div class="form-group col-md-12">
              <label>Address</label>
              {{ custform.address }}
            </div>
            <div class="form-group col-md-12">
              <p>
                {{custform.agreeterms}} By completing this booking I acknowledge
                I have read and accepted the
                <a href="{% url 'web:term_and_conditions' %}" title="Contact"
                  >Terms and Conditions
                </a>
                and
                <a href="{% url 'web:cancellation_policy' %}" title="Contact"
                  >Cancellation Policy .
                </a>
              </p>
            </div>
            <div class="form-group col-md-12 text-right">
              <input
                class="btn btn-primary"
                type="submit"
                id="pay-btn"
                value="Book now"
              />
            </div>
          </form>
        </div>

        <div class="col-md-6">
          <div class="col-md-2"></div>

          <div class="row col-md-10 border-round">
            <h3>Order Summary</h3>

            <table class="table">
                <tbody>
                <tr>
                  <th scope="col">CheckIn Date</th>
                  <td>{{ booking.checkin_date }}</td>
                </tr>
                
                <tr>
                  <th>CheckOut Date</th>
                  <td>{{ booking.checkout_date_display }}</td>
                </tr>
                <tr>
                  <th scope="col">No. of Guests</th>
                  <td>
                    {{ total_adults }} Adults {% if total_childs > 0 %} , {{
                    total_childs }} Children {% endif %}
                  </td>
                </tr>
              </tbody>
            </table>
            <hr />

            <div class="row mt">
              <div class="col-md-12">
                <!-- <div class="section-title">Order Summary</div> -->

                <table class="table table-borderless">
                  <thead>
                    <tr>
                      <th scope="col">Room Type</th>
                      <th>No. of Rooms</th>

                      <th class="text-right" scope="col">Price</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in bkd_room_type %}

                    <tr>
                      <th scope="row">{{ item.room.title }}</th>
                      <th>{{ item.reserved_rooms }}</th>
                      <th class="text-right">{{ item.price }}</th>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>

                <div class="row mt-4">
                  <div class="col-lg-2">
                    <div></div>
                    <p></p>
                  </div>
                  <div class="col-lg-10 text-right">

                    <div style="font-size: 15px; font-weight: 400">
                      <div><b>{{ extra_beds }} Extra Bed </b></div>
                      <div>₹{{ booking.total_extra_bed_price }}</div>
                    </div>
                    <hr class="mt-2 mb-2" />
                    {% if booking.total_price > booking.total_offer_price %}
                    <div
                      style="
                        font-size: 18px;
                        font-weight: 400;
                        color: rgb(106 106 106);
                      "
                    >
                      <div class="">Total</div>
                      <div class=""><s>₹{{ booking.total_price }}</s></div>
                    </div>

                    <div>
                      <div class="order-price">Offer Price</div>
                      <p>inclusive of all taxes</p>

                      <div class="order-price">₹{{ booking.total_offer_price }}</div>
                    </div>
                    {% else %}
                    <div>
                      <div class="order-price">Total</div>
                      <p class="text-muted">inclusive of all taxes</p>
                      <div class="order-price">₹{{ booking.total_price }}</div>
                    </div>

                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %} {% block scripts %}

<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
  //    var email =  document.getElementById('id_email').val()
  console.log();

  $(document).ready(function () {
    $("form").on("submit", function (event) {
      var email = $("#id_email").val();
      var phone = $("#id_phone").val();

      var options = {
        key: "{{ razorpay_merchant_key }}", // Enter the Key ID generated from the Dashboard
        amount: "{{ razorpay_amount }}",
        currency: "{{ currency }}",

        name: "DeluxeInn Payment",
        description: "Hotel Chennai",
        // "image": "{% static 'dashboard/img/icon.png' %}",
        order_id: "{{ razorpay_order_id }}",
        callback_url: "{{ callback_url }}",
        prefill: {
          // "name": "Gaurav Kumar",
          email: email,
          contact: phone,
        },
        notes: {
          address: "T'Nagar's Central Hotel",
        },
        "theme": {
            "color": "#440000"
        }
      };
      var rzp1 = new Razorpay(options);

      event.preventDefault();

      let $this = $(this);
      let url = "{% url 'web:create_user_data_ajax' %}";
      let method = $this.attr("method");

      $.ajax({
        type: method,
        url: url,
        dataType: "json",
        contentType: false,
        processData: false,
        data: new FormData(this),

        success: function (data) {
          if (data["status"] == "true") {
            rzp1.open();
          }
        },
        error: function (data) {},
      });

      // rzp1.on('payment.failed', function (response){
      //         alert(response.error.code);
      //         alert(response.error.description);
      //         alert(response.error.source);
      //         alert(response.error.step);
      //         alert(response.error.reason);
      //         alert(response.error.metadata.order_id);
      //         alert(response.error.metadata.payment_id);
      // });
    });
  });
</script>

{% endblock %}

templates/web/term_and_conditions.html
{% extends 'web/base.html' %} {% load static %} {% block content%}
<div class="site-main page-spacing">
  <section class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h2>Terms and Conditions</h2>
          <ol start="1">
            <p><li>The usual standard check-in time is 14:00 and checkout time is 12:00</li></p>
            <p>
              <li>
                Early check in and Late checkout is subject to availability and
                will be chargeable. Checkouts from 1200 to 1800 hours are
                subject to 50% of room rate and thereafter at 100%
              </li>
            </p>
            <p>
              <li>
                All arrivals prior to 6AM are billed from the previous night.
              </li>
            </p>
            <p>
              <li>
                All arrivals between 0600 to 1100 hours are subject to 50% of
                the room rate.
              </li>
            </p>
            <p>
              <li>
                In case of no-show or cancellation of a guaranteed reservation
                the resort reserves the right to levy retention charged for
                entire reserved stay.
              </li>
            </p>
            <p>
              <li>
                For any disputes in payments and any other legal disputes, the
                jurisdiction of the court will be in Chennai district Tamilnadu.
              </li>
            </p>
          </ol>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}

templates/web/test.html
<p>hello world</p>
<form action="" method="post">
    {% csrf_token %}
{{ form.as_p}}

<input type="submit">


</form>