account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.registration_view, name="home"),
    # path('admin/', admin.site.urls),
    path('account/', views.account_view, name="account"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('must-authenticate/', views.must_authenticate_view, name="must_authenticate"),
    path('register/', views.registration_view, name="register"),
    path('phone-otp/', views.phone_otp, name="phone_otp"),
    path('forgot-password/', views.forgot_password, name="forgot_password"),
    path('forgot-password-otp/', views.forgot_password_otp, name="forgot_password_otp"),
    path('forgot-password-new-password/', views.forgot_password_new_password, name="forgot_password_new_password"),
    path('reset-password/', views.reset_password, name="reset_password"),
    path('check-username/', views.check_username, name="check_username"),
    path('check-email/', views.check_email, name="check_email"),

    # path('auto_register/', views.auto_registration_view, name="auto_register"),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from dashboard import views

app_name = "dashboard"

urlpatterns = [
    path('', views.index, name="index"),   
    path('calender', views.calender, name="calender"),
    path('create-room', views.create_room, name="create_room"),
    path('offer-room', views.RoomOfferCreateView.as_view(), name="offer_room"),
    path('confirm-booking/', views.confirm_booking,name='confirm_booking'),
    path('invoice/<id>', views.booking_invoice,name='booking_invoice'),


    path('booking-room', views.booking_room, name="booking_room"),
    path('booking-listview', views.BookingListView.as_view(),name='booking_list_view'),
    path('online-booking-listview', views.OnlineBookingListView.as_view(),name='online_booking_list_view'),

    path('update-room/<int:id>', views.update_room,name='update_room'),
    path('delete-room/<int:id>', views.delete_room,name='delete_room'),

    path('list-room', views.room_list_view, name="room_list_view"),
    path('create-customer-ajax', views.create_customer_ajax, name="create_customer_ajax"),
    path('check-room-availabilty', views.check_room_availabilty, name="check_room_availabilty"),
    # path('get-notification',views.get_notification,name='get_notification',),
    path('account-autocomplete',views.account_autocomplete.as_view(),name='account_autocomplete',),

    path('get-extra-bed', views.get_extra_bed, name="get_extra_bed"),
    path('offer-list-view', views.OfferListView.as_view(),name='offer_list_view'),
    path('<int:id>/delete-offer', views.delete_offer,name='delete_offer'),
    path('update-offer/<int:id>', views.update_offer,name='update_offer'),
    path('<int:id>/account', views.account_detail_view,name='account_detail_view'),
    path('get-max-guests', views.get_max_guests, name="get_max_guests"),
    path('notifications-ajax', views.notifications_ajax, name="notifications_ajax"),
    path('mark-as-read-notifi-ajax', views.mark_as_read_notifi_ajax, name="mark_as_read_notifi_ajax"),

]

rbs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('admin/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('', include(('web.urls', 'web'), namespace='web')),
    path('accounts/', include(('account.urls', 'account'), namespace='account')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/forms.py
from django import forms
from .models import *
from dal import autocomplete
from django.forms.widgets import TextInput, Textarea,FileInput,NumberInput,DateInput,Select


class RoomForm(forms.ModelForm):
	class Meta:
		model = Room
		fields = ['title','price','new_price','max_adult','max_child','description','status','image','adult','child','no_of_rooms','extra_bed_price']
		widgets= {
			'title' : TextInput(attrs={'class': 'required form-control',}),						
			'price' : TextInput(attrs={'class': 'required form-control',}),			
			'new_price' : TextInput(attrs={'class': 'required form-control',}),					
			'max_adult' : NumberInput(attrs={'class': 'required form-control',}),			
			'max_child' : NumberInput(attrs={'class': 'required form-control',}),			
			'status' : TextInput(attrs={'class': 'required form-control',}),
			'image' : FileInput(attrs={'class': 'required form-control',}),	
			'description' : TextInput(attrs={'class': 'required form-control',}),
			'adult' : NumberInput(attrs={'class': 'required form-control',}),			
			'child' : NumberInput(attrs={'class': 'required form-control',}),
			'no_of_rooms' : NumberInput(attrs={'class': 'required form-control',}),	
			'extra_bed_price' : TextInput(attrs={'class': 'required form-control',}),					


		}

class OfferForm(forms.ModelForm):
	class Meta:
		model = Offer
		fields = ['title','room_type','offer_price','date']
		widgets= {
			'title' : TextInput(attrs={'class': 'required form-control',}),			
			'room_type' : Select(attrs={'class': 'required form-control',}),			
			'offer_price' : TextInput(attrs={'class': 'required form-control',}),			
			'date' : DateInput(attrs={'class': 'required form-control','type':'date'}),		
		}	

class BookingForm(forms.ModelForm):
	class Meta:
		model = Booking
		fields = ['account','checkin_date','checkout_date','booking_date','payment_type']
		widgets= {
			'account' :autocomplete.ModelSelect2(url='dashboard:account_autocomplete', attrs={'data-placeholder':'Select Customer','class':'form-control'},),		
			'checkin_date' : DateInput(attrs={'class': 'required form-control','type':'date'}),				
			'checkout_date' : DateInput(attrs={'class': 'required form-control','type':'date'}),	
			'payment_type' : TextInput(attrs={'class': 'required form-control'},),
		}	
# class RoomNumForm(forms.ModelForm):
# 	class Meta:
# 		model = Room_num
# 		fields = ['room_no','room_type']
# 		widgets= {
# 			'room_no' : TextInput(attrs={'class': 'required form-control',}),	
# 			'room_type' : Select(attrs={'class': 'required form-control',}),								
# 		}


class CustomAccountForm(forms.ModelForm):
	class Meta:
		model = Account
		fields = ('email', 'username','address','phone','first_name','last_name')
		widgets= {
			'username' : forms.TextInput(attrs={'class': 'required form-control',}),
			'first_name' : forms.TextInput(attrs={'class': 'required form-control',}),
			'last_name' : forms.TextInput(attrs={'class': 'required form-control',}),
			'address' : forms.Textarea(attrs={'class': 'required form-control',}),
			'email' : forms.NumberInput(attrs={'class': 'required form-control','type' : 'email'}),
			'phone' : forms.NumberInput(attrs={'class': 'required form-control','type' : 'tel','maxlength' : '10'}),
		}
		
class BookedRoomTypeForm(forms.ModelForm):
	class Meta:
		model = BookedRoomType
		fields = ['room']
		widgets= {
			'room': Select( attrs={'data-placeholder':'Select Customer','class':'form-control'},),
		}


class BookedRoomForm(forms.ModelForm):
	class Meta:
		model = BookedRoom
		fields = ['room','adult','child','extra_bed']
		widgets= {
			'room': Select( attrs={'data-placeholder':'Select Customer','class':'form-control selDiv room_input'},),
			'adult' : NumberInput(attrs={'class': 'required adult_input form-control','min':0, 'max':5,'value':0}),
			'child' : NumberInput(attrs={'class': 'required child_input form-control','min':0, 'max':5,'value':0}),
			'extra_bed' : TextInput(attrs={'class': 'required extrabed_input form-control','min':0, 'max':5}),
		}
		

dashboard/views.py
from datetime import time,date, timedelta, timezone 
# from datetime import strptime
import datetime,calendar
import pytz
from django.http import response
from django.shortcuts import (render,redirect,get_object_or_404,HttpResponseRedirect)
from .forms import *
from django.urls import reverse
from .models import *
from account.forms import *
from dal import autocomplete
import json
from django.http.response import HttpResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required,user_passes_test
from django.forms import formset_factory,modelformset_factory
from django.views.generic import(
    ListView,
    CreateView,
    DeleteView,
    UpdateView,
    DetailView
)
from account import models
from django.contrib.auth.mixins import LoginRequiredMixin
from main.functions import get_auto_id


user_login_required = user_passes_test(lambda user: user.is_admin)
def admin_required(view_func):
    decorated_view_func = login_required(user_login_required(view_func))
    return decorated_view_func

@admin_required
def index(request):
    context = {
        "title": "dashboard",
        "page_name":"Dashboard",
    }
    return render(request, 'dashboard/index.html', context)
    
@admin_required
def calender(request):
    date_format = "%Y-%m-%d"
    start_date = datetime.strptime(request.GET.get('start'), date_format).date()
    end_date = datetime.strptime(request.GET.get('end'), date_format).date()
    # print(start_date,end_date)

    obj = get_rooms_status(start_date,end_date)
    events = []
    for key,value in obj.items():
        dates = key
        for k,v in value.items():
            # print(date,k,v)
            color = "#08aceb"
            if v['filled_rooms'] == v['total_rooms']:
                color = "#398f07"
            elif v['free_rooms'] == v['total_rooms']:
                color = "#bdbcbb"
            row ={
                "title" : "{} : {}/{}".format(k,v['filled_rooms'],v['total_rooms']),
                "start": dates,
                "backgroundColor": color,
                # "url": 'http://google.com/'
            }
            events.append(row)
    obj = json.dumps(events)
    return HttpResponse(obj,content_type='application/javascript')




@admin_required
def create_room(request):
    if request.method == "POST":
        form = RoomForm(request.POST,request.FILES)
        if (form.is_valid()):
            form_data = form.save(commit=False)
            form_data.save()
            return redirect('dashboard:room_list_view')

            
    else:
        form = RoomForm()
    context = {
        "title": "Add Room",
        "form": form,
        "page_name":"add_room_type"
    }  
    return render(request, 'dashboard/room_create_view.html', context)




@admin_required
def booking_room(request):

    BookedRoomFormSet = formset_factory(BookedRoomForm,extra=1)
    if request.method == "POST":
        account_form = CustomAccountForm(request.POST)
        form = BookingForm(request.POST)
        booked_room_formset = BookedRoomFormSet(request.POST,prefix="booked_room_formset")
        if (form.is_valid()):
            form_data = form.save(commit=False)
            form_data.total_price = 0
            form_data.total_offer_price = 0
            form_data.total_extra_bed_price =int(0)
            date_format = "%Y-%m-%d"
            a = datetime.strptime(str(form_data.checkin_date), date_format)
            b = datetime.strptime(str(form_data.checkout_date), date_format)
            form_data.checkout_date_display= form_data.checkout_date
            form_data.checkout_date = form_data.checkout_date-timedelta(1)

            delta = b - a
            total_days= delta.days
            if(total_days > 0 ):


                if (booked_room_formset.is_valid()):
                    form_data.auto_id = get_auto_id(Booking)

                    form_data.save()  
                
                    rooms = Room.objects.all()
                    for room in rooms:
                        price = get_room_total_price(room,form_data.checkin_date,form_data.checkout_date)
                        offer_price = get_room_total_price_with_offer(room,form_data.checkin_date,form_data.checkout_date)

                        BookedRoomType.objects.create(
                            room=room,
                            booking=form_data,
                            reserved_rooms=0,
                            price = price,
                            offer_price = offer_price,
                            extra_bed_price = 0,
                            total_price = 0,
                            total_offer_price = 0,

                        )
                    for bookedroomform in booked_room_formset:
                        f_data = bookedroomform.save(commit=False)
                        extra_bed_price = f_data.extra_bed * f_data.room.extra_bed_price * total_days
                        bkd_room_type = BookedRoomType.objects.get(booking=form_data,room=f_data.room)
                        room_price = bkd_room_type.price
                        room_offer_price = bkd_room_type.offer_price

                        bkd_room_type.reserved_rooms = int(bkd_room_type.reserved_rooms) + int(1)

                        bkd_room_type.extra_bed_price =  extra_bed_price
                        f_data.total_price = room_price + extra_bed_price
                        f_data.offer_price = room_offer_price + extra_bed_price


                        bkd_room_type.total_price = f_data.total_price * bkd_room_type.reserved_rooms
                        bkd_room_type.total_offer_price = f_data.offer_price * bkd_room_type.reserved_rooms


                        bkd_room_type.save()
                        f_data.days = total_days
                        f_data.extra_bed = extra_bed_price/f_data.room.extra_bed_price/total_days
                        f_data.booked_room_type = bkd_room_type

                        form_data.total_price+=f_data.total_price
                        form_data.total_offer_price+=f_data.offer_price


                        form_data.total_extra_bed_price = form_data.total_extra_bed_price + bkd_room_type.extra_bed_price
                        form_data.auto_id = get_auto_id(Booking)
                       
                        f_data.save()

                    BookedRoomType.objects.filter(total_price = 0).delete()
                    form_data.save()
                    request.session['booking_id'] = form_data.auto_id
                    return redirect('dashboard:confirm_booking' )

                        
        else:
            print("not valid ..")
    else:
        form = BookingForm()
        booked_room_formset = BookedRoomFormSet(prefix="booked_room_formset")
        account_form = CustomAccountForm()
    context = {
        "title": "New booking",
        "form": form,
        # "room_type_formset":room_type_formset,
        "booked_room_formset":booked_room_formset,
        "account_form":account_form,
        "page_name":"booking_room",
    }  
    return render(request, 'dashboard/booking_create_view.html', context)

@admin_required
def confirm_booking(request):
    context ={}
    id = request.session['booking_id']
    # print("//////////////////////////////////////////////////////////////////////",id)
    if request.method == "POST":
           
        if(Booking.objects.filter(auto_id=id).exists):
            Booking.objects.filter(auto_id=id).update(is_Booking_confirmed =True)
            redirect_url = reverse('dashboard:booking_room')
            # print(redirect_url)
            response_data = {
                "title":"Confirm Booking",
                "status" : "true",
                "swal_text":"Booking Confirmed" ,
                "redirect_url":redirect_url,
                }
            return HttpResponse(json.dumps(response_data),content_type='application/javascript')

    else:        

        booking = get_object_or_404(Booking,auto_id = id)
        # print(booking)
        sub_total = booking.total_price-booking.total_extra_bed_price
        bkd_room_type = BookedRoomType.objects.filter(booking=booking)
        bookedroom= BookedRoom.objects.filter(booked_room_type__booking = booking)
        total_adults = 0
        total_childs = 0

        for item in bookedroom:
            total_adults +=item.adult
            total_childs +=item.child
        context.update({
        "booking": booking,
        "bkd_room_type" : bkd_room_type,
        "bookedroom" :bookedroom,
        "total_adults" :total_adults,
        "total_childs" :total_childs,
        "sub_total":sub_total,



        })
    # Booking.objects.filter(id=id,is_Booking_confirmed =False).delete()
    context.update({
        "title": "confirm-booking",
        "page_name":"booking_room",
    })  
    return render(request, 'dashboard/confirm_booking.html', context)


@admin_required
def create_customer_ajax(request):
    if request.method == "POST":
        account_form = CustomAccountForm(request.POST)
        if(account_form.is_valid()):
            form_data = account_form.save(commit=False)
            username = form_data.username

            print(username)
            if(Account.objects.filter(username=username).exists()):
                print("exists")

                response_data = {
                    "status" : "false",
                    }
                return HttpResponse(json.dumps(response_data),content_type='application/javascript')

            form_data.save()
            response_data = {
                "status" : "true",
                "click_class":".modal .close"
            }
            return HttpResponse(json.dumps(response_data),content_type='application/javascript')
        else:
            response_data = {
                "status" : "true",
                "swal_icon" : "warning",
                "swal_title" : "Validation error",

templates/dashboard/booking_create_view.html
{% extends 'dashboard/base.html' %} {% load static %} {% block content %}

<div class="main-content">
    <section class="section">

        <div class="row">
            <div class="col-12 col-sm-12 col-lg-8">
                <div class="card">
                    <div class="card-header">
                        <h4>Booking</h4>
                    </div>
                    <!-- <button id="create-customer-button"> CreateCustomer</button>
                    <form action="" method="post">
                        <div class="card-body">

                            {% csrf_token %}

                            {{ form.as_p }}

                        </div> -->
                        <form action="{% url 'dashboard:booking_room' %}" method="post">
                            {% csrf_token %}
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Account</label>
                                    {{ form.account }}
                                    <span class=" mt-1 d-block float-right btn-outline-primary btn-sm cursor-pointer " id="create-customer-button"> CreateCustomer</span>
                                </div>
                                
                                <div class="form-group">
                                    <label>Checkin Date</label>
                                    {{ form.checkin_date }}
                                </div>
                                <div class="form-group">
                                    <label>Checkout Date</label>
                                    {{ form.checkout_date }}
                                </div>
                                

                                <span class=" d-block float-right btn-outline-primary btn-sm cursor-pointer check-room-availability"
                                    data-url="{% url 'dashboard:check_room_availabilty' %}">
                                    Check Availability</span>
                                    
                                <p style="display: inline;" class="avail hide text-success">Available Rooms:</p>
                                <!-- <p  id="room-num" class=" avail hide "></p> -->
                                <table id="room-num" class="avail hide">
                                <tr>
                                    <td></td>
                                </tr>
                                </table>



                                <div class="formset_parent ">
                                    {{booked_room_formset.management_form }}
                                    {% for item in booked_room_formset %}
                                        <div class="form_set_row w-100 d-md-inline-flex border p-3 m-2 rounded">
                                            {{item}}
                                        </div>
                                        
                                    {% endfor %}

                                  
                                </div>
                                   

                                <div class="form-group">
                                    <label>Payment Type</label>
                                    {{ form.payment_type }}
                                </div>

                            </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary mr-1" type="submit">Submit</button>
                            <button class="btn btn-secondary" type="reset">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>


    <!-- ################## -->

    <div class="modal fade hide" id="create-bank-modal" tabindex="-1" role="dialog" aria-labelledby="formModal"
        style="display: block; padding-right: 15px;" aria-modal="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="formModal">Create Customer</h5>
                    <button type="button" class="form-modal-close close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="ajax" action="{% url 'dashboard:create_customer_ajax' %}" method="POST"
                        enctype="multipart/form-data">
                  
                        <label>First name</label>
                        <div class="input-group">
                            {{ account_form.first_name }}
                        </div>
                        <label>Last name</label>
                        <div class="input-group">
                            {{ account_form.last_name }}
                        </div>

                        <label for="username">Username</label>
                        <div class="input-group">
                            <input type="text" id="username" class="form-control check_username" name="username" value="" minlength="6"
                                data-url="{% url 'account:check_username' %}" required="required">
                            <div class="check_username_msg invalid-feedback" style="display: block;">Not available</div>
                            <div class="check_username_msg valid-feedback" style="display: none;">Available</div>
                        </div>

                        <label>Email</label>
                        <div class="input-group">
                            {{ account_form.email }}
                        </div>
                        <label>Address</label>
                        <div class="input-group">
                            {{ account_form.address }}
                        </div>
                        <label>Phone</label>
                        <div class="input-group">
                            {{ account_form.phone }}
                        </div>
                            {% csrf_token %}
                        <div class="form-group mb-0">
                        </div>
                        <button type="submit" class="btn btn-primary m-t-15">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-backdrop fade hide"></div>


    <!-- ############## -->


</div>


{% endblock %}



{% block scripts %}
<script src="{% static 'dashboard/js/jquery.formset.min.js' %}"></script>
<!-- <script src="{% static 'dashboard/bundles/editable-table/mindmup-editabletable.js' %}"></script> -->

<script type="text/javascript">

    $(document).ready(function () {
             
            $(".form_set_row").formset({
            prefix: "{{booked_room_formset.prefix}}",
            formCssClass: "dynamic-formset1",
            addText: "Add-Room",
            addCssClass: "btn btn-primary btn-sm ml-2   add_row",
            deleteCssClass: "delete-row ",
            deleteText: "<i class='fas fa-trash-alt btn btn-sm m-2 btn-danger'></i>",
            
        });

        $(".add_row").click(function(){
            $(".form_set_row").each(function() {
                let formset = $(this);
                formset.find("input").each(function() {
                    let $this = $(this);
                    let value = $this.val();
                    if(!value){
                        $this.val(0);
                    }
                    console.log("value : ",value);
                })
            })

            $(".formset_parent input").click(function(){
            let $this = $(this);
            console.log($this.val());
            console.log("clicked");

            if($this.val()==0){
                $this.val("")
            }
        })
        
        })
        $(".formset_parent input").click(function(){
            let $this = $(this);
            // console.log($this.val());
            // console.log("clicked");

            if($this.val()==0){
                $this.val("")
            }
        })

    });

</script>

<style>
    .form_set_row.dynamic-formset1{
        background-color: #f7f7f7;

   
    }
    .form_set_row label{
        padding-inline-start: 11px;
        width: 25rem;
        margin-top: 11px;      
    }

</style>

{{form.media}}
{{booked_room_formset.media}}


{% endblock %}

templates/dashboard/offer_list_view.html
{% extends 'dashboard/base.html' %}
 {% load static %}
  {% block content %}
<div class="main-content">
    <section class="section">

        <div class="row">
            <div class="col-12 col-sm-12 col-lg-6">
                <div class="card">
                    <div class="card-header">
                      <h4>Offers List</h4>
                    </div>
                    <div class="col-2 pt-2 ml-2">
                      <a href="{% url 'dashboard:offer_room' %}" class="btn btn-outline-primary">Add</a>
                    </div>

                    <div class="card-body">
                      <div class="section-title mt-0"></div>
                      <table class="table table-hover">
                        <thead>
                          <tr>
                            <th scope="col">Title</th>
                            <th>Date</th>

                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for offer in offers %}
                                <tr >
                                    <td scope="row">
                                    <a style="text-decoration:none;" class="text-dark" href="#"> {{ offer.title }}</a></td>
                                    <td>
                                      {{ offer.date }}
                                    </td>
                                    <td>
                                     
                                        <a href="{% url 'dashboard:update_offer' offer.id %}" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit">
                                            <i class="fas fa-pencil-alt"></i>
                                     </a>
                                      <form method="POST" style="display: inline;" action="{% url 'dashboard:delete_offer' offer.id %}">
                                        {% csrf_token %}
  
                                        <button type="submit" class="btn btn-danger btn-action mr-1" data-toggle="tooltip" title="Delete">
                                          <i class="fas fa-trash-alt"></i>
                                         </button>
                                       </form>
                                    </td>
                                </tr>
                             {% endfor %}
                        </tbody>
                      </table>
                  </div>
                </div>
            </div>
        </section>
    
    </div>
            <!-- Vertically Center
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalCenterTitle" aria-hidden="true" caller-id="">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalCenterTitle">Delete Offer</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Confirm Delete Offer 
                </div>
                <div class="modal-footer bg-whitesmoke br">
                <form method="POST" style="display: inline;" id="item-delete-form">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger" id="confirm-delete-item-button">Delete</button>
                  </form>

                  <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div> -->

{% endblock %}



<!-- {% block scripts %}
   
<script>
      $(document).on('click', '.confirm-delete', function () {
          // document.getElementById("item-delete-form").action = document.querySelector('#delete-offer').href

        $("#exampleModalCenter").attr("caller-id", $(this).attr("id"));

      });
      $(document).on('click', '#confirm-delete-item-button', function () {
          var caller = $("#confirm-delete-item-button").closest(".modal").attr("caller-id");
          // console.log(caller)
          window.location = $("#".concat(caller)).attr("href");
});
</script>
{% endblock %} -->